// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_rTj5SN0ctexIKsQUVRm5xbDYptdO-A',
    appId: '1:752333508178:web:5ee3ea95a5f77cb621198b',
    messagingSenderId: '752333508178',
    projectId: 'flutter-chat-app-a1959',
    authDomain: 'flutter-chat-app-a1959.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a1959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCy0Av5myGEYCo60nFu-_JfLfHLjEnq0',
    appId: '1:752333508178:android:da4f8c818d2a816021198b',
    messagingSenderId: '752333508178',
    projectId: 'flutter-chat-app-a1959',
    storageBucket: 'flutter-chat-app-a1959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEM4SdTnJJrP1dVZFjQIuE1LH2wHiWDSI',
    appId: '1:752333508178:ios:e37cb4fb1bf7518f21198b',
    messagingSenderId: '752333508178',
    projectId: 'flutter-chat-app-a1959',
    storageBucket: 'flutter-chat-app-a1959.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEM4SdTnJJrP1dVZFjQIuE1LH2wHiWDSI',
    appId: '1:752333508178:ios:e37cb4fb1bf7518f21198b',
    messagingSenderId: '752333508178',
    projectId: 'flutter-chat-app-a1959',
    storageBucket: 'flutter-chat-app-a1959.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe_rTj5SN0ctexIKsQUVRm5xbDYptdO-A',
    appId: '1:752333508178:web:3f22e40412cbc74721198b',
    messagingSenderId: '752333508178',
    projectId: 'flutter-chat-app-a1959',
    authDomain: 'flutter-chat-app-a1959.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a1959.firebasestorage.app',
  );

}